version: '3.8'

services:
  app:
    build:
      .
    ports:
      - "5000:80"
    expose:
      - 80

  db:
    image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04
    environment:
      - SA_PASSWORD=Secret#123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    expose:
      - 1433
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql

volumes:
  data: